version: '3'

services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    restart: always
