version: '3'
services:
  storyboard_mysql:
    image: mysql:5.7
    container_name: storyboard_mysql
    hostname: storyboard_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'storyboard'
      MYSQL_USER: 'marketak'
      MYSQL_PASSWORD: 'root_ROOT_1234'
      MYSQL_ROOT_PASSWORD: 'root_ROOT_1234'
    #ports:
    #  - '3306:3306'
    #expose:
    #  - '3306'
    #volumes:
    #  - my-db:/home/marketak/MySQL/mysql_volume
  storyboard_app:
    container_name: storyboard_app
    hostname: storyboard_app
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
    ports:
     - 8099:8080
    depends_on:
     - storyboard_mysql
  
