version: '3'
services:
  storyboard_mysql:
    command: [ "--max_connections=1000" ]
    image: mysql:5.7
    container_name: storyboard_mysql
    hostname: storyboard_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'storyboard'
      MYSQL_USER: 'marketak'
      MYSQL_PASSWORD: 'root_ROOT_1234'
      MYSQL_ROOT_PASSWORD: 'root_ROOT_1234'
    volumes:
      - ./resources/storyboard.sql:/docker-entrypoint-initdb.d/dump.sql
  storyboard_app:
    container_name: storyboardapp
    hostname: storyboardapp
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
    ports:
     - 8099:8080
    depends_on:
     - storyboard_mysql
  storyboard_nginx:
    image: nginx:stable
    container_name: storyboard_nginx
    hostname: storyboard_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
