version: '3.9'
services:
  apache:
    #image: ubuntu/apache2
    container_name: apache2
    build:
      context: proxy_server
      dockerfile: Dockerfile
    ports:
    - 80:80
    volumes:
    - ./sites-available:/etc/apache2/sites-available
